name = "testsuite"
description = "testsuite for markdown-renderer"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["testsuite"]

[build-switches]
development.Ada_Version = "Ada2022"
development.optimization = ["-O0"]
development.contracts = "Yes"
development.style_checks = ["-gnaty", "-gnaty-B"]
"*".debug_info = "Yes"

[build-profiles]
"*" = "development"

[[depends-on]]
markdown_renderer = "*"

[[pins]]
markdown_renderer = { path='..' }

[[depends-on]]
trendy_test = "~0.0.4"
